(letrec ((a* (λ (x c)
                (if (null? x)
                    c
                    (if (pair? x)
                        (a* (cdr x) (+ c (car x)))
                        #f)))))
  (letrec ((a (λ (x)
                 (if (or (null? x)
                         (pair? x))
                     (a* x 0)
                     #f))))
    (a (cons (a (cons 5 (cons 4 (cons 2 '()))))
             (cons (a (cons 1 (cons 3 (cons 10 '()))))
                   '())))))
